/**
 * Error Monitor Helper for E2E Tests
 *
 * Captures console errors and uncaught exceptions during test execution.
 * Use this to catch runtime errors (like infinite loops, null references)
 * that would otherwise pass silently in E2E tests.
 *
 * @example Basic usage with fixture (recommended):
 * ```typescript
 * import { test, expect } from '../fixtures/error-monitoring';
 *
 * test('my test', async ({ page, errorMonitor }) => {
 *   await page.goto('/my-page');
 *   // Do stuff...
 *   // Errors are automatically asserted at the end of the test
 * });
 * ```
 *
 * @example Manual usage:
 * ```typescript
 * import { createErrorMonitor } from '../helpers/error-monitor';
 *
 * test('my test', async ({ page }) => {
 *   const monitor = createErrorMonitor(page);
 *   await page.goto('/my-page');
 *   // Do stuff...
 *   monitor.assertNoErrors('after navigation');
 * });
 * ```
 *
 * @example With custom ignored patterns:
 * ```typescript
 * const monitor = createErrorMonitor(page, {
 *   ignoredPatterns: [
 *     'Expected error message',
 *     /some-regex-pattern/,
 *   ],
 * });
 * ```
 */

import { Page, expect } from '@playwright/test';

export interface ErrorMonitorOptions {
  /**
   * Patterns for errors to ignore. Can be strings (substring match) or RegExp.
   * These are merged with DEFAULT_IGNORED_PATTERNS — they do not replace them.
   */
  ignoredPatterns?: (string | RegExp)[];
  /**
   * Whether to capture warnings (console.warn) in addition to errors.
   * Default: false
   */
  captureWarnings?: boolean;
}

export interface CapturedError {
  type: 'pageerror' | 'console.error' | 'console.warn';
  message: string;
  timestamp: Date;
  stack?: string;
}

/**
 * Default ignored patterns are split into two categories:
 *
 * 1. FRAMEWORK-SPECIFIC: errors generated by common frameworks (React, Vite,
 *    Next.js) that are not real application bugs. These belong in the template.
 *
 * 2. PROJECT-SPECIFIC: errors unique to your application's libraries or
 *    architecture. Add these via the `ignoredPatterns` option or
 *    `addIgnoredPattern()` at runtime — do NOT add them here.
 *
 * When adopting this template, review the list below and remove any patterns
 * for frameworks your project does not use.
 */
const DEFAULT_IGNORED_PATTERNS: (string | RegExp)[] = [
  // --- Universal (all projects) ---

  // Favicon errors are benign — most dev servers don't serve a favicon
  'favicon',
  // Expected when testing error states or when backend is down
  'Failed to load resource: net::ERR_CONNECTION_REFUSED',

  // --- WebSocket (common in dev servers) ---

  // String-form WebSocket errors
  'WebSocket connection failed',
  // Browser-format: "WebSocket connection to 'ws://...' failed: Error in..."
  /WebSocket connection to .* failed/,
  // Generic WebSocket error from dev server clients
  '[ws] WebSocket error',

  // --- React ---

  // React hydration warnings in dev mode (not real errors)
  'Hydration failed',
  // React dev mode warning about updating state during render
  'Cannot update a component',

  // --- Vite ---

  // Vite HMR noise during hot module replacement
  '[vite]',

  // --- Next.js (remove if not using Next.js) ---

  // RSC payload fetch errors during client-side navigation in dev mode
  'Failed to fetch RSC payload',
  // Internal navigation fallback messages
  'Falling back to browser navigation',
  // fetchServerResponse errors during client-side navigation
  'fetchServerResponse',
];

export class ErrorMonitor {
  private errors: CapturedError[] = [];
  private page: Page;
  private options: ErrorMonitorOptions;
  private isListening = false;

  constructor(page: Page, options: ErrorMonitorOptions = {}) {
    this.page = page;
    this.options = {
      ignoredPatterns: [...DEFAULT_IGNORED_PATTERNS, ...(options.ignoredPatterns || [])],
      captureWarnings: options.captureWarnings ?? false,
    };
    this.setupListeners();
  }

  private setupListeners(): void {
    if (this.isListening) return;
    this.isListening = true;

    // Capture uncaught exceptions (thrown errors, runtime crashes)
    this.page.on('pageerror', (error) => {
      const message = error.message || String(error);
      if (!this.isIgnoredError(message)) {
        this.errors.push({
          type: 'pageerror',
          message,
          timestamp: new Date(),
          stack: error.stack,
        });
      }
    });

    // Capture console.error calls
    this.page.on('console', (msg) => {
      if (msg.type() === 'error') {
        const text = msg.text();
        if (!this.isIgnoredError(text)) {
          this.errors.push({
            type: 'console.error',
            message: text,
            timestamp: new Date(),
          });
        }
      } else if (this.options.captureWarnings && msg.type() === 'warning') {
        const text = msg.text();
        if (!this.isIgnoredError(text)) {
          this.errors.push({
            type: 'console.warn',
            message: text,
            timestamp: new Date(),
          });
        }
      }
    });
  }

  private isIgnoredError(text: string): boolean {
    return this.options.ignoredPatterns!.some((pattern) => {
      if (typeof pattern === 'string') {
        return text.includes(pattern);
      }
      return pattern.test(text);
    });
  }

  /**
   * Get all captured errors (excluding ignored ones)
   */
  getErrors(): CapturedError[] {
    return [...this.errors];
  }

  /**
   * Check if any errors have been captured
   */
  hasErrors(): boolean {
    return this.errors.length > 0;
  }

  /**
   * Assert that no errors have been captured.
   * Throws with detailed error information if errors exist.
   *
   * @param context - Optional context string to include in error message
   */
  assertNoErrors(context?: string): void {
    const errorMessages = this.errors.map((e) => {
      const prefix = e.type === 'pageerror' ? '[Uncaught]' : '[Console]';
      return `  ${prefix} ${e.message}${e.stack ? `\n    Stack: ${e.stack.split('\n').slice(0, 3).join('\n    ')}` : ''}`;
    });

    const message = context
      ? `Runtime errors detected in "${context}":\n${errorMessages.join('\n')}`
      : `Runtime errors detected:\n${errorMessages.join('\n')}`;

    expect(this.errors, message).toEqual([]);
  }

  /**
   * Clear all captured errors.
   * Useful if you expect errors in one part of the test but want to
   * verify no errors in a subsequent part.
   */
  clear(): void {
    this.errors = [];
  }

  /**
   * Add additional patterns to ignore (useful for test-specific expected errors).
   * Returns `this` for chaining.
   *
   * @example
   * errorMonitor
   *   .addIgnoredPattern('Expected error')
   *   .addIgnoredPattern(/timeout/i);
   */
  addIgnoredPattern(pattern: string | RegExp): this {
    this.options.ignoredPatterns!.push(pattern);
    return this;
  }
}

/**
 * Factory function for creating an ErrorMonitor instance.
 *
 * @param page - Playwright Page instance
 * @param options - Optional configuration
 * @returns ErrorMonitor instance
 */
export function createErrorMonitor(page: Page, options?: ErrorMonitorOptions): ErrorMonitor {
  return new ErrorMonitor(page, options);
}
